# Generated by Django 5.1.2 on 2024-10-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="rating",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
